name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo Pune1999@ | docker login -u sankettupe1 --password-stdin
    - run: sudo docker build -f Dockerfile -t  sihbruteforce2020/startup:latest .
    - run: docker push sihbruteforce2020/startup:latest
